# Omakase Ruby styling for Rails
#inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable

# Don't force a comment at the top of every class
Style/Documentation:
  Exclude:
    - "**/*.rb"

Metrics/MethodLength:
  Exclude:
    - "db/**/*"

# We're almost certainly never going to need localisation in this app
Rails/I18nLocaleTexts:
  Enabled: false
