---
- name: "Setup servers"
  hosts: "all"
  become: true
  pre_tasks:
    - name: "Create Active Storage directory"
      ansible.builtin.file:
        path: "{{ lookup('env', 'RAILS_ACTIVE_STORAGE_DIR') }}"
        state: "directory"
        owner: "1000"
        group: "1000"
        mode: "0755"
  roles:
    - role: "system_locale"
      vars:
        system_locale_name: "en_AU.UTF-8"
    - role: "system_harden_ssh"
      vars:
        system_harden_ssh_ports: [22]
        system_harden_ssh_permit_root_login: "yes"
        system_harden_ssh_permit_password_authentication: "no"
        system_harden_ssh_public_key: "{{ lookup('env', 'ANSIBLE_SSH_PUBLIC_KEY') }}"
    - role: "docker_install"
    - role: "postgres_install_docker"
      vars:
        postgres_install_docker_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
        postgres_install_docker_user: "{{ lookup('env', 'POSTGRES_USERNAME') }}"
        postgres_install_docker_network: "{{ lookup('env', 'POSTGRES_DOCKER_NETWORK') }}"
        postgres_install_docker_port: "{{ lookup('env', 'POSTGRES_PORT') }}"
        postgres_install_docker_container_name: "{{ lookup('env', 'POSTGRES_HOST') }}"
    - role: "postgres_restic_backup"
      vars:
        postgres_restic_backup_s3_endpoint: "{{ lookup('env', 'RESTIC_POSTGRES_S3_ENDPOINT') }}"
        postgres_restic_backup_s3_bucket: "{{ lookup('env', 'RESTIC_POSTGRES_S3_BUCKET') }}"
        postgres_restic_backup_s3_access_key: "{{ lookup('env', 'RESTIC_POSTGRES_S3_ACCESS_KEY') }}"
        postgres_restic_backup_s3_secret_key: "{{ lookup('env', 'RESTIC_POSTGRES_S3_SECRET_KEY') }}"
        postgres_restic_backup_restic_password: "{{ lookup('env', 'RESTIC_PASSWORD') }}"
        postgres_restic_backup_postgres_container: "{{ lookup('env', 'POSTGRES_HOST') }}"
        postgres_restic_backup_postgres_user: "{{ lookup('env', 'POSTGRES_USERNAME') }}"
    - role: "restic_backup"
      vars:
        restic_backup_dir: "/opt/active-storage-backup"
        restic_backup_cron_job_name: "active-storage-restic-backup"
        restic_backup_s3_endpoint: "{{ lookup('env', 'RESTIC_ACTIVE_STORAGE_S3_ENDPOINT') }}"
        restic_backup_s3_bucket: "{{ lookup('env', 'RESTIC_ACTIVE_STORAGE_S3_BUCKET') }}"
        restic_backup_s3_access_key: "{{ lookup('env', 'RESTIC_ACTIVE_STORAGE_S3_ACCESS_KEY') }}"
        restic_backup_s3_secret_key: "{{ lookup('env', 'RESTIC_ACTIVE_STORAGE_S3_SECRET_KEY') }}"
        restic_backup_restic_password: "{{ lookup('env', 'RESTIC_PASSWORD') }}"
        restic_backup_path: "{{ lookup('env', 'RAILS_ACTIVE_STORAGE_DIR') }}"
