---
- name: "Setup servers"
  hosts: "all"
  become: true
  roles:
    - role: "system_locale"
      vars:
        system_locale_name: "en_AU.UTF-8"
    - role: "system_harden_ssh"
      vars:
        system_harden_ssh_ports: [22]
        system_harden_ssh_permit_root_login: "yes"
        system_harden_ssh_permit_password_authentication: "no"
        system_harden_ssh_public_key: "{{ lookup('env', 'ANSIBLE_SSH_PUBLIC_KEY') }}"
    - role: "docker_install"
    - role: "postgres_install_docker"
      vars:
        postgres_install_docker_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
        postgres_install_docker_user: "{{ lookup('env', 'POSTGRES_USERNAME') }}"
        postgres_install_docker_network: "{{ lookup('env', 'POSTGRES_DOCKER_NETWORK') }}"
        postgres_install_docker_port: "{{ lookup('env', 'POSTGRES_PORT') }}"
        postgres_install_docker_container_name: "{{ lookup('env', 'POSTGRES_HOST') }}"
