{
 "title": "Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "JQC RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "alias(stats.gauges.cadvisor.jqc-*.*.web.1.memory_working_set, 'web')"
    },
    {
     "target": "alias(stats.gauges.cadvisor.jqc-*.*.worker.1.memory_working_set, 'worker')"
    },
    {
     "target": "alias(stats.gauges.cadvisor.dokku.postgres.*.memory_working_set, 'postgres')"
    },
    {
     "target": "alias(stats.gauges.cadvisor.dokku.redis.*.memory_working_set, 'redis')"
    }
   ]
  },
  {
   "title": "Disk storage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(collectd-jqc-*.df-root.df_complex-free, 'Available')"
    },
    {
     "target": "alias(collectd-jqc-*.df-root.df_complex-used, 'Used')"
    }
   ]
  },
  {
   "title": "System RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$C * 1", "type": "math" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(collectd-jqc-*.cpu-*.percent-active, 1)"
    }
   ]
  }
 ]
}