---
name: "cicd"

env:
  SOPS_AGE_KEY: "${{ secrets.SOPS_AGE_KEY }}"
  # `pr-123` for PRs, `production` for master
  ENVIRONMENT: >-
    ${{ github.event.pull_request.number
    && format('pr-{0}', github.event.pull_request.number)
    || (github.ref_name == 'master' && 'production' || github.ref_name) }}

"on":
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

concurrency:
  group: "${{ github.head_ref || github.ref_name }}"
  cancel-in-progress: false

jobs:
  lint-test-deploy:
    runs-on: "ubuntu-latest"
    env:
      RAILS_MASTER_KEY: "${{ secrets.RAILS_MASTER_KEY }}"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v6"

      - uses: "jdx/mise-action@v4.0.1"
        with:
          version: "2026.3.1"

      - name: "Cache Ruby gems"
        uses: "actions/cache@v5"
        with:
          path: "vendor/bundle"
          key: "${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}"
          restore-keys: |
            "${{ runner.os }}-gems-"

      - name: "Cache Python dependencies"
        uses: "actions/cache@v5"
        with:
          path: "infrastructure/ansible/.venv"
          key: >-
            ${{ runner.os }}-uv-
            ${{ hashFiles('infrastructure/ansible/uv.lock') }}
          restore-keys: >-
            ${{ runner.os }}-uv-

      - name: "Run checks"
        run: |
          bundle config set --local path vendor/bundle
          just install
          just lint

      - name: "Deploy"
        run: |
          just deploy "${{ env.ENVIRONMENT }}"
