name: "Lint"

on:
  workflow_call:
    inputs: {}
    secrets:
      RAILS_MASTER_KEY:
        required: true

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: "npm"

      - name: Lint code for consistent style
        run: |
          npm ci
          bundle exec rake lint
